### ISSUE TITLE
paswoord 2 x ingeven 

### ISSUE THREAD

**Issue by kikipluche** [locals-world/locals-pm#5]

**Comment by kingflurkel** [comment]
Jawel, dat is klaar. 
Ik heb aanvullend ook een backup ding toegevoegd, en dus ook een import file functie. 
Verder is het wachtwoord niet meer in localstorage, maar in sessionstorage. Dat wil dus zeggen dat wanneer je je browser afsluit en terug start, je het wachtwoord opnieuw moet ingeven.
